
##################################################################
# TetraMAX Reference Methodology Pattern Debug Data Script       #
# Script: tmax_debug_patterns.tcl                                #
# Version: O-2018.06-SP2 (October 8, 2018)                       #
# Copyright (C) 2014-2018 Synopsys, Inc. All rights reserved.    #
##################################################################

##################################################################
# This script produces parallel strobe data to help debug        #
# mismatches in parallel-load Verilog simulation. It is only     #
# required for compression-mode patterns.  When scan-mode        #
# patterns are simulated, the scan chain name and position are   #
# printed even without the parallel strobe data generated by     #
# this script.                                                   #
##################################################################

###############################################################
# SETUP: Settings for overall execution                       #
###############################################################

set_messages -log tmax_debug_patterns.log -replace
report_version -full
set TMAX_SCRIPTS_ROOT "./rm_tmax_scripts"
set TMAX_SETUP_ROOT "./rm_setup"
source -echo ${TMAX_SETUP_ROOT}/tmax_setup.tcl
if { $TMAX_DEBUG_MODE } {
   set_messages -level expert
}
if { $TMAX_COMPRESSION_MODE } {
   set tmax_file_ext comp
} else {
   set tmax_file_ext scan
   # Parallel strobe data is not needed to debug scan-mode patterns.
   quit
}

# First, read the image used to generate the pattern being debugged:
read_image ${RESULTS_DIR}/${DESIGN_NAME}_trans.${tmax_file_ext}.img

# A -num_processes setting is in the image file, so it must be reset here.
if { $TMAX_NUM_PROCS > 1 } {
   set_atpg -num_processes $TMAX_NUM_PROCS
   set_simulation -num_processes $TMAX_NUM_PROCS
} else {
   set_atpg -num_processes 0
   set_simulation -num_processes 0
}

##################################################################
# RESIMULATE: Resimulate patterns to save parallel strobe data   #
##################################################################

# Set the pattern file, using the binary pattern set if available.
set_patterns -external ${RESULTS_DIR}/${DESIGN_NAME}_trans.${tmax_file_ext}.bin.gz

# Make sure that simulation settings match those used for ATPG.
set_simulation -shift_cycles 1
#set_simulation -timing_exceptions_for_stuck_at
report_settings simulation

# Slack-Based Transition Fault Testing settings do not matter for logic simulation.

run_simulation -parallel_strobe_data_file ${RESULTS_DIR}/${DESIGN_NAME}_resim.${tmax_file_ext}.psd -replace

# Write the debug pattern set. Please read the comments at the top of this file.
# If you need patterns in the 1999 version of STIL, instead of the default
# 2005 version, change to -format stil99 and remove -cellnames type.
write_patterns ${RESULTS_DIR}/${DESIGN_NAME}_resim.${tmax_file_ext}.stil.gz -external -format stil -replace -compress gzip -cellnames type
#
# This setting is required to run write_testbench in batch mode:
setenv LTRAN_SHELL 1
write_testbench -input ${RESULTS_DIR}/${DESIGN_NAME}_resim.${tmax_file_ext}.stil.gz -output ${RESULTS_DIR}/${DESIGN_NAME}_resim.${tmax_file_ext}.maxtb -replace -config_file ${TMAX_SCRIPTS_ROOT}/tmax_debug_config.tcl -parameters " -v_file ${NETLIST_FILES} -v_lib ${TMAX_LIBRARY_FILES} -sim_script vcs -log ${RESULTS_DIR}/${DESIGN_NAME}_resim.${tmax_file_ext}.maxtb.log "

# A subset of the patterns can be written into the testbench to save runtime
# in Verilog simulation. Use the -first and -last parameters. For example,
# to simulate only from pattern N to pattern M, use this command:
#write_testbench -input ${RESULTS_DIR}/${DESIGN_NAME}_resim.${tmax_file_ext}.stil.gz -output ${RESULTS_DIR}/${DESIGN_NAME}_resim.${tmax_file_ext}.maxtb -replace -config_file ${TMAX_SCRIPTS_ROOT}/tmax_debug_config.tcl -parameters " -first N -last M -v_file ${NETLIST_FILES} -v_lib ${TMAX_LIBRARY_FILES} -sim_script vcs -log ${RESULTS_DIR}/${DESIGN_NAME}_resim.${tmax_file_ext}.maxtb.log "

##################################################################
#    End of TetraMAX RM Pattern Update script                    #
##################################################################

report_summaries cpu_usage memory_usage
quit
